os:
  - linux

dist: trusty

language: cpp

compiler:
  - clang
  - gcc

env:
  - QT5_BUILD=ON
  - QT5_BUILD=OFF

script: cmake -DCMAKE_BUILD_TYPE=Debug -DQT5_BUILD=$QT5_BUILD . && make

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - if [ "$QT5_BUILD" = "ON" ]; then sudo apt-get install -qq qtbase5-dev qttools5-dev qttools5-dev-tools; fi
  - if [ "$QT5_BUILD" = "OFF" ]; then sudo apt-get install -qq libqt4-dev libqjson-dev; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++; fi
